apiVersion: v2
name: acm-setup
description: A Helm chart to configure ACM to deploy multiple environments via GitOps
type: application

version: 0.1.0
appVersion: 0.1.16

mantainers:
  - name: Asier Cidon
    email: acidonpe@redhat.com

dependencies:
  - name: infra-acm
    repository: 'https://autstudent.github.io/infra-acm'
    version: 0.1.1
    condition: infra-acm.enabled